# Generated by Django 4.2 on 2023-05-26 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('position', models.CharField(max_length=50)),
                ('dateOfListing', models.DateField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('category', models.CharField(default='none', max_length=30)),
                ('wantEducation', models.BooleanField(default=False)),
                ('wantLanguages', models.BooleanField(default=False)),
                ('wantExperience', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OfferResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.CharField(max_length=255)),
                ('image', models.FileField(upload_to='', verbose_name='Your CV')),
                ('experience', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('education', models.CharField(blank=True, max_length=50, null=True)),
                ('knownLanguages', models.CharField(blank=True, max_length=255, null=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobOffer.joboffer')),
            ],
        ),
    ]
