# Generated by Django 4.2 on 2023-05-21 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('position', models.CharField(max_length=50)),
                ('dateOfListing', models.DateField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('category', models.CharField(default='none', max_length=30)),
                ('wantEducation', models.BooleanField(default=False)),
                ('wantLanguages', models.BooleanField(default=False)),
                ('wantExperience', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.user')),
            ],
        ),
    ]
