# Generated by Django 4.2 on 2023-05-21 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('JobOffer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='', verbose_name='Your CV')),
                ('experience', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('education', models.CharField(blank=True, max_length=50, null=True)),
                ('knownLanguages', models.CharField(blank=True, max_length=255, null=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobOffer.joboffer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
