# Generated by Django 4.2 on 2023-05-21 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobOffer', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerresponse',
            name='image',
            field=models.FileField(upload_to='', verbose_name='Your CV'),
        ),
    ]
